package com.mycompany.exceptions;

public class Exceptions {

    public static void main(String[] args) {

        Calculator calculator = new Calculator();
        int result = calculator.division(2, 0);
        
       /* 
        try{
            int result = calculator.division(4, 0);
            System.out.println(result);
        } catch(Exception exception) {
            System.out.println("Ha ocurrido un problema");
            System.out.println(exception);
            //int result = 2/0;
        } finally{ //se ejecuta siempre sin importar la excepci칩n
            System.out.println("bloque para imprimir siempre");
        }
        */
       /*
        try{
            int[] numbers = new int[3];
            numbers[5] = 2/0;
        } catch (ArithmeticException e){
            System.out.println("Operaci칩n no permitida"); 
        } catch (ArrayIndexOutOfBoundsException e){
            System.out.println("Posici칩n de array no v치lida");
        } catch (Exception e){
            System.out.println("Ha ocurrido un problema");
        }
        */  
    }
}
